[package]
name = "llama-test"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8.35"
llama-cpp-2 = { version = "0.1.87", git = "https://github.com/KennanHunter/llama-cpp-rs.git", default-features = false }
