[target.x86_64-apple-darwin]
rustflags = [
    # "-C",
    # "link-arg=-fuse-ld=lld",
    "-l",
    "dylib:+verbatim=/opt/homebrew/opt/libomp/lib/libomp.dylib",
]

[target.aarch64-apple-darwin]
rustflags = [
    # "-C",
    # "link-arg=-fuse-ld=lld",
    "-l",
    "dylib:+verbatim=/opt/homebrew/opt/libomp/lib/libomp.dylib",
]
