[target.x86_64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    "-C",
    "link-arg=-fopenmp",
    "-C",
    "link-arg=-L/opt/homebrew/opt/libomp/lib",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    "-C",
    "link-arg=-fopenmp",
    "-C",
    "link-arg=-L/opt/homebrew/opt/libomp/lib",
]
